language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services: redis
before_install:
  - sudo apt-get install openssh-client openssh-server
  - sudo systemctl start sshd
  - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCdOVWd5rN1Q7UN4jLRrEoQgVYSXHXVX2oIu0RZNpJNaBIov/B8bzqgAv0ueQ6B2+tRDN1FFrtLNTFQDJEDi1azN1MEWGokuyjh8BFKdj/zYIIbTb0BK0LKTb5DZXaqnm+mWuXqf42nAyeU7Re0nvnajYvg3AuZAWq9DZhhG9wSbQ==' > /home/travis/.ssh/authorized_key
  - cp helpers/key /home/travis/.ssh/key
  - chmod 400 /home/travis/.ssh/key
install:
  - pip install -r requirements.pip
  - nohup celery worker --app actions --config celeryconfig.py -E -n 1.%h --loglevel=info &
  - sleep 10
script:
  - pytest test.py