language: python
python:
  - "3.6"
#  - "3.7"
services: redis
before_install:
  - sudo apt-get install openssh-client openssh-server
  - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCdOVWd5rN1Q7UN4jLRrEoQgVYSXHXVX2oIu0RZNpJNaBIov/B8bzqgAv0ueQ6B2+tRDN1FFrtLNTFQDJEDi1azN1MEWGokuyjh8BFKdj/zYIIbTb0BK0LKTb5DZXaqnm+mWuXqf42nAyeU7Re0nvnajYvg3AuZAWq9DZhhG9wSbQ==' > /home/travis/.ssh/authorized_keys
  - cp tools/key /home/travis/.ssh/key
  - chmod 400 /home/travis/.ssh/key
  - sudo sed -i 's/#PasswordAuthentication no/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - sudo service ssh restart
  - pip install pipenv
install:
  - pipenv install --system
  - nohup celery worker --app actions --config celeryconfig.py -E -n 1.%h --loglevel=info &
  - sleep 10
script:
  - pytest --cov=./ tests/*
